In [131]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [132]:
import numpy as np

In [133]:
np.asarray(revenue)
np.asarray(expenses)

array([12051.82,  5695.07, 12319.2 , 12089.72,  8658.57,   840.2 ,
        3285.73,  5821.12,  6976.93, 16618.61, 10054.37,  3803.96])

In [134]:
#Solution
#Calculate Profit As The Differences Between Revenue And Expenses
profit = np.subtract(revenue,expenses)

In [135]:
profit

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [136]:
#Calculate Tax As 30% Of Profit And Round To 2 Decimal Points
tax = profit*0.3

In [137]:
tax

array([  756.801,   573.417, -1112.337,  -874.293,  -179.976,  2179.572,
        2463.165,  1183.491,   998.517,  -671.595,   197.88 ,  3488.862])

In [138]:
profitwithouttax = np.subtract(profit,tax)
profitwithouttax

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [139]:
profitwhithouttax=np.round(profitwithouttax,2)

In [140]:
profitwhithouttax

array([ 1765.87,  1337.97, -2595.45, -2040.02,  -419.94,  5085.67,
        5747.38,  2761.48,  2329.87, -1567.06,   461.72,  8140.68])

In [141]:
#Calculate The Profit Margin As Profit After Tax Over Revenue
#Round To 2 Decimal Points, Then Multiply By 100 To Get %
profit_margin = profitwithouttax/revenue
profit_margin

array([ 0.12116163,  0.17589956, -0.30139698, -0.22233524, -0.05211096,
        0.62743886,  0.49993433,  0.28276199,  0.22608449, -0.10897492,
        0.04309514,  0.52746804])

In [142]:
profit_margin = profit_margin * 100
profit_margin.round()

array([ 12.,  18., -30., -22.,  -5.,  63.,  50.,  28.,  23., -11.,   4.,
        53.])

In [143]:
#Calculate The Mean Profit After Tax For The 12 Months
mean_pat = sum(profit)/len(profit)
mean_pat

2500.9733333333334

In [144]:
#Find The Months With Above-Mean Profit After Tax
good_months = list([])
for i in range (0, len(revenue)):
    good_months.append(revenue[i] > expenses[i])
good_months

[True, True, False, False, False, True, True, True, True, False, True, True]

In [145]:
#Bad Months Are The Opposite Of Good Months!
bad_months = list([])
for i in range (0, len(revenue)):
    bad_months.append(not (good_months[i]))
bad_months

[False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False]

In [146]:
#The Best Month Is Where Profit After Tax Was Equal To The Maximum
best_month = list([])
for i in range (0, len(revenue)):
    best_month.append(profit[i] == max(profit))
best_month

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True]

In [147]:
#The Worst Month Is Where Profit After Tax Was Equal To The Minimum
worst_month = list([])
for i in range (0, len(revenue)):
    worst_month.append(profit[i] == min(profit))
worst_month

[False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [148]:
#Convert All Calculations To Units Of One Thousand Dollars and print them
revenue = np.divide(revenue,1000)
revenue = np.round(revenue)
print ("Revenue :") 
print (revenue)

Revenue :
[15.  8.  9.  9.  8.  8. 11. 10. 10. 14. 11. 15.]


In [150]:
for i in range(0, len(expenses)):
    b=i+1
    expenses[i]=np.divide(expenses[i],1000)
    expenses[i] = np.round(expenses[i])
    print ("Revenue from the ", b," month is :", expenses[i])

Revenue from the  1  month is : 12.0
Revenue from the  2  month is : 6.0
Revenue from the  3  month is : 12.0
Revenue from the  4  month is : 12.0
Revenue from the  5  month is : 9.0
Revenue from the  6  month is : 1.0
Revenue from the  7  month is : 3.0
Revenue from the  8  month is : 6.0
Revenue from the  9  month is : 7.0
Revenue from the  10  month is : 17.0
Revenue from the  11  month is : 10.0
Revenue from the  12  month is : 4.0


In [151]:
for i in range(0, len(profit)):
    profit[i]=np.divide(profit[i],1000)
    profit[i]=np.round(profit[i])
print("Profit :")
print(profit)


Profit :
[ 3.  2. -4. -3. -1.  7.  8.  4.  3. -2.  1. 12.]


In [153]:
for i in range(0, len(profitwhithouttax)):
    profitwhithouttax[i]=np.divide(profitwhithouttax[i],1000)
    profitwhithouttax[i]=np.round(profitwhithouttax[i])
print("Profit without tax :")
print(profitwithouttax)

Profit without tax :
[ 1765.869  1337.973 -2595.453 -2040.017  -419.944  5085.668  5747.385
  2761.479  2329.873 -1567.055   461.72   8140.678]


In [159]:
# here we are going to say the month and the value
for i in range(0,len(good_months)):
    position = i+1;
    if good_months[i]:# for good month
        print("On the ",position," month was good we maked:", profitwhithouttax[i])
    else:# for bad month
        print("On the ",position," month was bad we maked:", profitwhithouttax[i])


On the  1  month was good we maked: 2.0
On the  2  month was good we maked: 1.0
On the  3  month was bad we maked: -3.0
On the  4  month was bad we maked: -2.0
On the  5  month was bad we maked: -0.0
On the  6  month was good we maked: 5.0
On the  7  month was good we maked: 6.0
On the  8  month was good we maked: 3.0
On the  9  month was good we maked: 2.0
On the  10  month was bad we maked: -2.0
On the  11  month was good we maked: 0.0
On the  12  month was good we maked: 8.0


In [163]:
for i in range(0,len(best_month)):
    position = i+1;
    if best_month[i]:
        print("The best month was the ",position," and we maked:", profitwhithouttax[i])


The best month was the  12  and we maked: 8.0


In [166]:
for i in range(0,len(worst_month)):
    position = i+1;
    if worst_month[i]:
        print("The worst month was the ",position," and we maked:", profitwhithouttax[i])

The worst month was the  3  and we maked: -3.0
